insert into sinh_vien_tinh_nguyen.dia_chi 
value
(1, N'Hồng Lĩnh',N'Hà Tĩnh'), (2, N'Việt Yên',N'Bắc Giang'), (3, N'Lục Nam',N'Bắc Giang'),
 (4, N'Trực Ninh',N'Nam Định'), (5, N'Nam Từ Liêm',N'Hà Nội'), (6, N'Văn Giang',N'Hưng Yên'),
 (7, N'Thanh Xuân',N'Hà Nội'), (8, N'Hương Sơn',N'Hà Tĩnh'), (9, N'Sơn La',N'Sơn La'),
 (10, N'Bắc Ninh',N'Bắc Ninh'), (11, N'Yên Phong',N'Bắc Ninh'), (12, N'Tĩnh Gia',N'Thanh Hóa'),
 (13, N'Quỳnh Phụ',N'Thái Bình'), (14, N'Xuân Trường',N'Nam Định'), (15, N'Nghĩa Đàn',N'Nghệ An'),
 (16, N'Yên Định',N'Thanh Hóa'), (17, N'Quốc Oai',N'Hà Nội'), (18, N'Ứng Hòa',N'Hà Nội'),
 (19, N'Thái Thụy',N'Thái Bình'), (20, N'Đống Đa',N'Hà Nội'), (21, N'Triệu Sơn',N'Thanh Hóa'),
 (22, N'Hoài Đức',N'Hà Nội'), (23, N'Yên Bái',N'Yên Bái'), (24, N'Long Biên',N'Hà Nội'),
 (25, N'Tây Hồ',N'Hà Nội'), (26, N'Đô Lương',N'Nghệ An'), (27, N'Sóc Sơn',N'Hà Nội'),
 (28, N'Thái Nguyên',N'Thái Nguyên'), (29, N'Tiên Du',N'Bắc Ninh'), (30, N'Hà Đông',N'Hà Nội'),
 (31, N'Ninh Bình',N'Ninh Bình'), (32, N'Thạch Thành',N'Thanh Hóa'), (33, N'Ngô Quyền',N'Hải Phòng'),
 (34, N'Ngọc Lặc',N'Thanh Hóa'), (35, N'Ba Đình',N'Hà Nội'), (36, N'Sơn Tây',N'Hà Nội'),
 (37, N'Nam Trực',N'Nam Định'), (38, N'Kiến Xương',N'Thái Bình'), (39, N'Nga Sơn',N'Thanh Hóa'),
 (40, N'Thanh Hóa',N'Thanh Hóa'), (41, N'Nghi Lộc',N'Nghệ An'), (42, N'Khoái Châu',N'Hưng Yên'),
 (43, N'Thiệu Hóa',N'Thanh Hóa'), (44, N'Thanh Oai',N'Hà Nội'), (45, N'Thái Bình',N'Thái Bình'),
 (46, N'Diễn Châu',N'Nghệ An'), (47, N'Hoằng Hóa',N'Thanh Hóa'), (48, N'Kiến An',N'Hải Phòng'),
 (49, N'Nam Đàn',N'Nghệ An'), (50, N'Đông Anh',N'Hà Nội'), (51, N'Thuỷ Nguyên',N'Hải Phòng'),
 (52, N'Thanh Liêm',N'Hà Nam'), (53, N'Phú Xuyên',N'Hà Nội'), (54, N'Vinh',N'Nghệ An'),
 (55, N'Thường Tín',N'Hà Nội'), (56, N'Tiên Lữ',N'Hưng Yên'), (57, N'Ninh Giang',N'Hải Dương'),
 (58, N'Lý Nhân',N'Hà Nam'), (59, N'Như Xuân',N'Thanh Hóa'), (60, N'Hai Bà Trưng',N'Hà Nội'),
 (61, N'Yên Thành',N'Nghệ An'), (62, N'Thanh Hà',N'Hải Dương'), (63, N'Thạch Thất',N'Hà Nội'),
 (64, N'Anh Sơn',N'Nghệ An'), (65, N'Vũ Thư',N'Thái Bình'), (66, N'Gia Bình',N'Bắc Ninh'),
 (67, N'Buôn Ma Thuột',N'Đắk Lắk'), (68, N'Phúc Thọ',N'Hà Nội'), (69, N'Hải An',N'Hải Phòng'),
 (70, N'Thái Hòa',N'Nghệ An'), (71, N'Thanh Trì',N'Hà Nội'), (72, N'Bắc Kạn',N'Bắc Kạn'),
 (73, N'Cẩm Phả',N'Quảng Ninh'), (74, N'Bình Xuyên',N'Vĩnh Phúc'), (75, N'Yên Mỹ',N'Hưng Yên'),
 (76, N'Đan Phượng',N'Hà Nội'), (77, N'An Lão',N'Hải Phòng'), (78, N'Hậu Lộc',N'Thanh Hóa'),
 (79, N'Lê Chân',N'Hải Phòng'), (80, N'Kỳ Anh',N'Hà Tĩnh'), (81, N'Hoàn Kiếm',N'Hà Nội'),
 (82, N'Hải Dương',N'Hải Dương'), (83, N'Hạ Long',N'Quảng Ninh'), (84, N'Sa Thầy',N'Kon Tum'),
 (85, N'Hoa Lư',N'Ninh Bình');